# BD
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=genesis_secreto_genesis_secreto_123456
jwt.expiration=86400000

# CONTEXT PATH
server.servlet.context-path=/api/v1

# SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.url=openapi.yml
springdoc.swagger-ui.path=/swagger-ui.html